[build]
  base    = "college_management_system/frontend"
  command = "npm run build"
  publish = "college_management_system/frontend/build"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
